---
#
# Ansible managed
#
repository:
  description: Install or uninstall software on your system.
  homepage: https://robertdebock.nl/
  topics: software, ansible, molecule, tox, playbook, hacktoberfest
