---
- name: test if software_packages is set correctly
  assert:
    that:
      - software_packages | length > 0
      - software_packages is iterable
    quiet: yes
  when:
    - software_packages is defined

- name: test if item.name in software_packages is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    quiet: yes
  loop: "{{ software_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - software_packages is defined

- name: test if item.state in software_packages is set correctly
  assert:
    that:
      - item.state in [ "present", "absent" ]
    quiet: yes
  loop: "{{ software_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - software_packages is defined
    - item.state is defined
