---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.software
      software_packages:
        - name: nano
        - name: tcpdump
          state: absent

  post_tasks:
    - name: Check nano
      ansible.builtin.package:
        name: nano
        state: present
      register: software_check_nano
      failed_when:
        - software_check_nano is changed

    - name: Check tcpdump
      ansible.builtin.package:
        name: tcpdump
        state: absent
      register: software_check_tcpdump
      failed_when:
        - software_check_tcpdump is changed
